{
    "foreachItems": [
        {
            "@odata.type": "#Microsoft.Dynamics.CRM.new_actualapprovalperson",
            "@odata.id": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)",
            "@odata.etag": 'W/"95687721"',
            "@odata.editLink": "new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)",
            "_new_approvalpersonuser_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_new_approvalpersonuser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_new_approvalpersonuser_value@odata.type": "#Guid",
            "_new_approvalpersonuser_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "statecode@OData.Community.Display.V1.FormattedValue": "Active",
            "statecode": 0,
            "_new_documentid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_DocumentId",
            "_new_documentid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_document",
            "_new_documentid_value@odata.type": "#Guid",
            "_new_documentid_value": "50619cf4-5f93-ee11-be37-000d3ab53bdd",
            "statuscode@OData.Community.Display.V1.FormattedValue": "Pending",
            "statuscode": 100000000,
            "createdon@OData.Community.Display.V1.FormattedValue": "12/5/2023 1:57 PM",
            "createdon@odata.type": "#DateTimeOffset",
            "createdon": "2023-12-05T11:57:34Z",
            "new_type@OData.Community.Display.V1.FormattedValue": "parallel",
            "new_type": 100000000,
            "_new_routeid_value@OData.Community.Display.V1.FormattedValue": "SOW - Initial Review - Standard template - GP is not ok",
            "_new_routeid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_RouteId",
            "_new_routeid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_route",
            "_new_routeid_value@odata.type": "#Guid",
            "_new_routeid_value": "db12c1b3-bb8e-ee11-8179-000d3adf7b4b",
            "new_sequence@OData.Community.Display.V1.FormattedValue": "1",
            "new_sequence": 1,
            "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
            "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_ownerid_value@odata.type": "#Guid",
            "_ownerid_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_new_position_value@OData.Community.Display.V1.FormattedValue": "Presale",
            "_new_position_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Position",
            "_new_position_value@Microsoft.Dynamics.CRM.lookuplogicalname": "position",
            "_new_position_value@odata.type": "#Guid",
            "_new_position_value": "a6b64756-2f5e-ee11-be6f-000d3adf74a3",
            "modifiedon@OData.Community.Display.V1.FormattedValue": "12/5/2023 1:57 PM",
            "modifiedon@odata.type": "#DateTimeOffset",
            "modifiedon": "2023-12-05T11:57:34Z",
            "new_approvaltype@OData.Community.Display.V1.FormattedValue": "Review",
            "new_approvaltype": 100000000,
            "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_modifiedby_value@odata.type": "#Guid",
            "_modifiedby_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "new_actualapprovalpersonid@odata.type": "#Guid",
            "new_actualapprovalpersonid": "052df174-6593-ee11-be37-000d3ab53bdd",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value@odata.type": "#Guid",
            "_createdby_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "MiratechGroup",
            "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
            "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
            "_owningbusinessunit_value@odata.type": "#Guid",
            "_owningbusinessunit_value": "eb033659-3771-e911-a9a7-000d3ab0f91d",
            "_new_routeapprovalstepsid_value@OData.Community.Display.V1.FormattedValue": "1",
            "_new_routeapprovalstepsid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_RouteApprovalStepsId",
            "_new_routeapprovalstepsid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_routeapprovalsteps",
            "_new_routeapprovalstepsid_value@odata.type": "#Guid",
            "_new_routeapprovalstepsid_value": "e073713d-6593-ee11-be37-000d3ab53bdd",
            "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_owninguser_value@odata.type": "#Guid",
            "_owninguser_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_LinkEntityAliasPrefixowninguser.domainname@OData.Community.Display.V1.AttributeName": "domainname",
            "_LinkEntityAliasPrefixowninguser.domainname": "Oleksii.Solodchuk@miratechgroup.com",
            "_LinkEntityAliasPrefixowninguser.fullname@OData.Community.Display.V1.AttributeName": "fullname",
            "_LinkEntityAliasPrefixowninguser.fullname": "Solodchuk, Oleksii",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@OData.Community.Display.V1.AttributeName": "new_accountid",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@OData.Community.Display.V1.FormattedValue": "Fabrikam, Inc.",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@Microsoft.Dynamics.CRM.lookuplogicalname": "account",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@odata.type": "#Guid",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid": "88cea450-cb0c-ea11-a813-000d3a1b1223",
            "new_DocumentId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_DocumentId/$ref",
            "new_DocumentId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_DocumentId",
            "new_RouteId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_RouteId/$ref",
            "new_RouteId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_RouteId",
            "ownerid@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/ownerid/$ref",
            "ownerid@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/ownerid",
            "new_Position@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_Position/$ref",
            "new_Position@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_Position",
            "owningbusinessunit@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/owningbusinessunit/$ref",
            "owningbusinessunit@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/owningbusinessunit",
            "new_RouteApprovalStepsId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_RouteApprovalStepsId/$ref",
            "new_RouteApprovalStepsId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/new_RouteApprovalStepsId",
            "createdby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/createdby/$ref",
            "createdby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/createdby",
            "createdonbehalfby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/createdonbehalfby/$ref",
            "createdonbehalfby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/createdonbehalfby",
            "modifiedby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/modifiedby/$ref",
            "modifiedby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/modifiedby",
            "modifiedonbehalfby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/modifiedonbehalfby/$ref",
            "modifiedonbehalfby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/modifiedonbehalfby",
            "owningteam@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/owningteam/$ref",
            "owningteam@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/owningteam",
            "owninguser@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/owninguser/$ref",
            "owninguser@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(052df174-6593-ee11-be37-000d3ab53bdd)/owninguser",
        },
        {
            "@odata.type": "#Microsoft.Dynamics.CRM.new_actualapprovalperson",
            "@odata.id": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)",
            "@odata.etag": 'W/"95687727"',
            "@odata.editLink": "new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)",
            "_new_approvalpersonuser_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_new_approvalpersonuser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_new_approvalpersonuser_value@odata.type": "#Guid",
            "_new_approvalpersonuser_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "statecode@OData.Community.Display.V1.FormattedValue": "Active",
            "statecode": 0,
            "_new_documentid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_DocumentId",
            "_new_documentid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_document",
            "_new_documentid_value@odata.type": "#Guid",
            "_new_documentid_value": "50619cf4-5f93-ee11-be37-000d3ab53bdd",
            "statuscode@OData.Community.Display.V1.FormattedValue": "Pending",
            "statuscode": 100000000,
            "createdon@OData.Community.Display.V1.FormattedValue": "12/5/2023 1:57 PM",
            "createdon@odata.type": "#DateTimeOffset",
            "createdon": "2023-12-05T11:57:35Z",
            "new_type@OData.Community.Display.V1.FormattedValue": "parallel",
            "new_type": 100000000,
            "_new_routeid_value@OData.Community.Display.V1.FormattedValue": "SOW - Initial Review - Standard template - GP is not ok",
            "_new_routeid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_RouteId",
            "_new_routeid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_route",
            "_new_routeid_value@odata.type": "#Guid",
            "_new_routeid_value": "db12c1b3-bb8e-ee11-8179-000d3adf7b4b",
            "new_sequence@OData.Community.Display.V1.FormattedValue": "1",
            "new_sequence": 1,
            "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
            "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_ownerid_value@odata.type": "#Guid",
            "_ownerid_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_new_position_value@OData.Community.Display.V1.FormattedValue": "Presale",
            "_new_position_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Position",
            "_new_position_value@Microsoft.Dynamics.CRM.lookuplogicalname": "position",
            "_new_position_value@odata.type": "#Guid",
            "_new_position_value": "a6b64756-2f5e-ee11-be6f-000d3adf74a3",
            "modifiedon@OData.Community.Display.V1.FormattedValue": "12/5/2023 1:57 PM",
            "modifiedon@odata.type": "#DateTimeOffset",
            "modifiedon": "2023-12-05T11:57:35Z",
            "new_approvaltype@OData.Community.Display.V1.FormattedValue": "Approve",
            "new_approvaltype": 100000001,
            "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_modifiedby_value@odata.type": "#Guid",
            "_modifiedby_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "new_actualapprovalpersonid@odata.type": "#Guid",
            "new_actualapprovalpersonid": "0b2df174-6593-ee11-be37-000d3ab53bdd",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value@odata.type": "#Guid",
            "_createdby_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "MiratechGroup",
            "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
            "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
            "_owningbusinessunit_value@odata.type": "#Guid",
            "_owningbusinessunit_value": "eb033659-3771-e911-a9a7-000d3ab0f91d",
            "_new_routeapprovalstepsid_value@OData.Community.Display.V1.FormattedValue": "1",
            "_new_routeapprovalstepsid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_RouteApprovalStepsId",
            "_new_routeapprovalstepsid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_routeapprovalsteps",
            "_new_routeapprovalstepsid_value@odata.type": "#Guid",
            "_new_routeapprovalstepsid_value": "520d7843-6593-ee11-be37-000d3ab53bdd",
            "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_owninguser_value@odata.type": "#Guid",
            "_owninguser_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_LinkEntityAliasPrefixowninguser.domainname@OData.Community.Display.V1.AttributeName": "domainname",
            "_LinkEntityAliasPrefixowninguser.domainname": "Oleksii.Solodchuk@miratechgroup.com",
            "_LinkEntityAliasPrefixowninguser.fullname@OData.Community.Display.V1.AttributeName": "fullname",
            "_LinkEntityAliasPrefixowninguser.fullname": "Solodchuk, Oleksii",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@OData.Community.Display.V1.AttributeName": "new_accountid",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@OData.Community.Display.V1.FormattedValue": "Fabrikam, Inc.",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@Microsoft.Dynamics.CRM.lookuplogicalname": "account",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@odata.type": "#Guid",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid": "88cea450-cb0c-ea11-a813-000d3a1b1223",
            "new_DocumentId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_DocumentId/$ref",
            "new_DocumentId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_DocumentId",
            "new_RouteId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_RouteId/$ref",
            "new_RouteId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_RouteId",
            "ownerid@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/ownerid/$ref",
            "ownerid@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/ownerid",
            "new_Position@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_Position/$ref",
            "new_Position@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_Position",
            "owningbusinessunit@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/owningbusinessunit/$ref",
            "owningbusinessunit@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/owningbusinessunit",
            "new_RouteApprovalStepsId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_RouteApprovalStepsId/$ref",
            "new_RouteApprovalStepsId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/new_RouteApprovalStepsId",
            "createdby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/createdby/$ref",
            "createdby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/createdby",
            "createdonbehalfby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/createdonbehalfby/$ref",
            "createdonbehalfby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/createdonbehalfby",
            "modifiedby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/modifiedby/$ref",
            "modifiedby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/modifiedby",
            "modifiedonbehalfby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/modifiedonbehalfby/$ref",
            "modifiedonbehalfby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/modifiedonbehalfby",
            "owningteam@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/owningteam/$ref",
            "owningteam@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/owningteam",
            "owninguser@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/owninguser/$ref",
            "owninguser@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(0b2df174-6593-ee11-be37-000d3ab53bdd)/owninguser",
        },
        {
            "@odata.type": "#Microsoft.Dynamics.CRM.new_actualapprovalperson",
            "@odata.id": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)",
            "@odata.etag": 'W/"95687731"',
            "@odata.editLink": "new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)",
            "_new_approvalpersonuser_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_new_approvalpersonuser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_new_approvalpersonuser_value@odata.type": "#Guid",
            "_new_approvalpersonuser_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "statecode@OData.Community.Display.V1.FormattedValue": "Active",
            "statecode": 0,
            "_new_documentid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_DocumentId",
            "_new_documentid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_document",
            "_new_documentid_value@odata.type": "#Guid",
            "_new_documentid_value": "50619cf4-5f93-ee11-be37-000d3ab53bdd",
            "statuscode@OData.Community.Display.V1.FormattedValue": "Pending",
            "statuscode": 100000000,
            "createdon@OData.Community.Display.V1.FormattedValue": "12/5/2023 1:57 PM",
            "createdon@odata.type": "#DateTimeOffset",
            "createdon": "2023-12-05T11:57:37Z",
            "new_type@OData.Community.Display.V1.FormattedValue": "parallel",
            "new_type": 100000000,
            "_new_routeid_value@OData.Community.Display.V1.FormattedValue": "SOW - Initial Review - Standard template - GP is not ok",
            "_new_routeid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_RouteId",
            "_new_routeid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_route",
            "_new_routeid_value@odata.type": "#Guid",
            "_new_routeid_value": "db12c1b3-bb8e-ee11-8179-000d3adf7b4b",
            "new_sequence@OData.Community.Display.V1.FormattedValue": "1",
            "new_sequence": 1,
            "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
            "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_ownerid_value@odata.type": "#Guid",
            "_ownerid_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_new_position_value@OData.Community.Display.V1.FormattedValue": "Presale",
            "_new_position_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Position",
            "_new_position_value@Microsoft.Dynamics.CRM.lookuplogicalname": "position",
            "_new_position_value@odata.type": "#Guid",
            "_new_position_value": "a6b64756-2f5e-ee11-be6f-000d3adf74a3",
            "modifiedon@OData.Community.Display.V1.FormattedValue": "12/5/2023 1:57 PM",
            "modifiedon@odata.type": "#DateTimeOffset",
            "modifiedon": "2023-12-05T11:57:37Z",
            "new_approvaltype@OData.Community.Display.V1.FormattedValue": "Visa",
            "new_approvaltype": 100000002,
            "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_modifiedby_value@odata.type": "#Guid",
            "_modifiedby_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "new_actualapprovalpersonid@odata.type": "#Guid",
            "new_actualapprovalpersonid": "e3a41a7a-6593-ee11-be37-000d3adeaf2a",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "Solodchuk, Oleksii",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value@odata.type": "#Guid",
            "_createdby_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "MiratechGroup",
            "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
            "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
            "_owningbusinessunit_value@odata.type": "#Guid",
            "_owningbusinessunit_value": "eb033659-3771-e911-a9a7-000d3ab0f91d",
            "_new_routeapprovalstepsid_value@OData.Community.Display.V1.FormattedValue": "1",
            "_new_routeapprovalstepsid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_RouteApprovalStepsId",
            "_new_routeapprovalstepsid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_routeapprovalsteps",
            "_new_routeapprovalstepsid_value@odata.type": "#Guid",
            "_new_routeapprovalstepsid_value": "f12f8849-6593-ee11-be37-000d3ab53bdd",
            "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_owninguser_value@odata.type": "#Guid",
            "_owninguser_value": "f73e8e0a-4828-ed11-9db1-0022489a9b8c",
            "_LinkEntityAliasPrefixowninguser.domainname@OData.Community.Display.V1.AttributeName": "domainname",
            "_LinkEntityAliasPrefixowninguser.domainname": "Oleksii.Solodchuk@miratechgroup.com",
            "_LinkEntityAliasPrefixowninguser.fullname@OData.Community.Display.V1.AttributeName": "fullname",
            "_LinkEntityAliasPrefixowninguser.fullname": "Solodchuk, Oleksii",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@OData.Community.Display.V1.AttributeName": "new_accountid",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@OData.Community.Display.V1.FormattedValue": "Fabrikam, Inc.",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@Microsoft.Dynamics.CRM.lookuplogicalname": "account",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid@odata.type": "#Guid",
            "_LinkEntityAliasPrefixnew_DocumentId.new_accountid": "88cea450-cb0c-ea11-a813-000d3a1b1223",
            "new_DocumentId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_DocumentId/$ref",
            "new_DocumentId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_DocumentId",
            "new_RouteId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_RouteId/$ref",
            "new_RouteId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_RouteId",
            "ownerid@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/ownerid/$ref",
            "ownerid@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/ownerid",
            "new_Position@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_Position/$ref",
            "new_Position@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_Position",
            "owningbusinessunit@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/owningbusinessunit/$ref",
            "owningbusinessunit@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/owningbusinessunit",
            "new_RouteApprovalStepsId@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_RouteApprovalStepsId/$ref",
            "new_RouteApprovalStepsId@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/new_RouteApprovalStepsId",
            "createdby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/createdby/$ref",
            "createdby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/createdby",
            "createdonbehalfby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/createdonbehalfby/$ref",
            "createdonbehalfby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/createdonbehalfby",
            "modifiedby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/modifiedby/$ref",
            "modifiedby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/modifiedby",
            "modifiedonbehalfby@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/modifiedonbehalfby/$ref",
            "modifiedonbehalfby@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/modifiedonbehalfby",
            "owningteam@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/owningteam/$ref",
            "owningteam@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/owningteam",
            "owninguser@odata.associationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/owninguser/$ref",
            "owninguser@odata.navigationLink": "https://miratech.crm4.dynamics.com/api/data/v9.1/new_actualapprovalpersons(e3a41a7a-6593-ee11-be37-000d3adeaf2a)/owninguser",
        },
    ]
}
